version : "3"

services:
  db:
    container_name: mariadb
    image : mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user
    ports:
      - "3306:3306"

  django:
    container_name : django-server
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/django
    ports:
      - "8000:8000"
    entrypoint: ./wait-for-it.sh db:3306 --
    command:
      - bash
      - -c
      - ./start.sh
    depends_on:
      - db
    environment:
      - JWT_SECRET_KEY=jhpark
      - JWT_ALGORITHM=HS256
